### ISSUE TITLE
XWT widgets disposed on background thread

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#4974]
Just opening and closing VSMac, the following XWT errors are shown about widgets getting disposed on background thread:

```
** (MonoDevelop:42816): WARNING **: Gtk operations should be done on the main Thread
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Gtk.Application.AssertMainThread()
   at Gtk.Widget.set_Events(EventMask value)
   at Xwt.GtkBackend.WidgetBackend.DisableEvent(Object eventId)
   at Xwt.Backends.BackendHost.Dispose()
   at Xwt.XwtComponent.Dispose(Boolean release_all)
   at Xwt.Widget.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

> VS bug [#625261](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/625261)

**Comment by Therzok** [comment]
That's a finalizer. Seems to be a bug in Xwt for handling Disposing on UI thread on finalization.

**Comment by sevoku** [comment]
Looks like https://github.com/mono/xwt/pull/760 (https://github.com/mono/xwt/pull/760/files#diff-cdfa687ee1b34a39c15576d6c32e6effR134) caused this, @slluis reverted the change with https://github.com/mono/xwt/pull/834

**Comment by Therzok** [comment]
Closing as the problematic fix was reverted.
