### ISSUE TITLE
Error in QuickTaskStrip

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#5188]
Seeing a lot of this error on master

```
ERROR [2018-06-25 16:40:53Z]: An unhandled exception has occurred. Terminating MonoDevelop? False
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutable[T](IEnumerable`1 items)
   at MonoDevelop.AnalysisCore.Gui.ResultsEditorExtension.get_QuickTasks()
   at MonoDevelop.SourceEditor.QuickTasks.QuickTaskStrip.Update(IQuickTaskProvider provider)
   at MonoDevelop.SourceEditor.SourceEditorWidget.DecoratedScrolledWindow.HandleTasksUpdated(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at MonoDevelop.AnalysisCore.Gui.ResultsEditorExtension.OnTasksUpdated(EventArgs e)
   at MonoDevelop.AnalysisCore.Gui.ResultsEditorExtension.ResultsUpdater.IdleHandler()
   at GLib.Idle.IdleProxy.Invoke(IntPtr data)
   at GLib.SourceProxy.HandlerInternal(IntPtr data)
```

**Comment by mhutch** [comment]
This appears to have been fixed in 564ff2075dea3b2f3a616bb99d9858c3677fc26d
