### ISSUE TITLE
Browse button does nothing

### ISSUE THREAD

**Issue by OptimusPyne** [mono/monodevelop#5501]
Pulled down monodevelop and built using visual studio this morning. I have the latest .net framework installed, using Windows 10. Repro sets:
Open MonoDevelop
Expand project.
Right click on references.
Go to .Net Assembly tab.
Press Browse...
Nothing happens.

**Comment by OptimusPyne** [comment]
Determined it is any attempt to use a file explorer, such as with file->open or file->Save As.

**Comment by mrward** [comment]
Can you attach the IDE log after reproducing the problem? IDE logs should be found in:

~/AppData/Local/MonoDevelop/{version}/Logs/

**Comment by OptimusPyne** [comment]
[Ide.2018-07-24__14-52-53.log](https://github.com/mono/monodevelop/files/2224982/Ide.2018-07-24__14-52-53.log)
This should be the minimum log to show issue.

**Comment by mrward** [comment]
It does not look like a project compiled correctly for some reason. How did you compile monodevelop?

```
An unhandled exception has occurred. Terminating MonoDevelop? False
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages.resources" was correctly embedded or linked into assembly "Microsoft.WindowsAPICodePack.Shell" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages.get_EnsureReadonlyCannotBeChanged()
   at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.set_EnsureReadOnly(Boolean value)
   at Microsoft.WindowsAPICodePack.Dialogs.CommonOpenFileDialog..ctor()
   at MonoDevelop.Platform.CustomCommonOpenFileDialog..ctor()
   at MonoDevelop.Platform.OpenFileDialogHandler.Run(OpenFileDialogData data)
   at MonoDevelop.Components.Extensions.PlatformDialog`1.Run()
   at MonoDevelop.Components.Extensions.SelectFileDialog`1.Run()
   at MonoDevelop.Ide.Projects.AssemblyReferencePanel.HandleClicked(Object sender, EventArgs e)
```

**Comment by OptimusPyne** [comment]
I downlaoded and installs prereqs based on https://github.com/mono/md-website/blob/gh-pages/developers/building-monodevelop.md#prerequisites-and-source
Then I cloned the repo using git clone https://github.com/mono/monodevelop --recursive
Then opened main.sln in visual studio and built it.

**Comment by mrward** [comment]
I normally use the main/winbuild.bat file to build monodevelop on Windows. Not tried using Visual Studio to build it.

**Comment by OptimusPyne** [comment]
Rebuilt using main/winbuild.bat. No change.

**Comment by OptimusPyne** [comment]
Compiling monodevelop does produce 94 warnings, no errors. It looks like manby of them are F# related:
FSC : warning FS0087: Invalid assembly name 'FSharp.Compiler.UnitTests

**Comment by OptimusPyne** [comment]
Is there any more information I can provide?

**Comment by Therzok** [comment]
WindowsAPICodePack seems busted. Not sure why the antivirus flags it.

**Comment by mrward** [comment]
So presumably this EmbeddedResource definition is changing the default resource name that is embedded for the WindowsAPICodePack - https://github.com/mono/monodevelop/commit/d7651cba75f13f87f59bb45335b36ae4d3a77b99

**Comment by francescofinotto** [comment]
now compile but still can't open file chooser, i've debugged a bit and found that it is raised an exception 
![immagine](https://user-images.githubusercontent.com/14017970/43231192-a3125f78-906b-11e8-857f-e1496dffd0f3.png)
and that when the CommandManager recive the command to open file manager and rise an exception that is :" Message = "Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure \"Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages.resources\" was correctly embedded or linked into assembly \"Microsoft.WindowsAPICodePack..."

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.1070 (release-7.7)

Author: Kirill Osenkov
Commit: 3b31545f0bd76ae67568aaac32103cf77315596a (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Author: Kirill Osenkov
Commit: 3b31545f0bd76ae67568aaac32103cf77315596a (xamarin/monodevelop)
