### ISSUE TITLE
Investigate performance in MdTextViewLineCollection

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5576]
Looks like http://source.monodevelop.com/#MonoDevelop.SourceEditor/Mono.TextEditor/Gui/MdTextViewLineCollection.cs,ef0d50f4be35eb95 may be inefficient. 

Also see comments from Todd in this PR: 
https://github.com/mono/monodevelop/pull/5564

> VS bug [#657459](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657459)

**Comment by Therzok** [comment]
Tried a new ASP.NET web app (no MVC), writing in the site.js file gives me as a side effect of the PR:
```
ERROR [2018-08-03 01:41:51Z]: Failed assertion at Mono.TextEditor.MdTextViewLineCollection.Add(Int32 logicalLineNumber, Mono.TextEditor.DocumentLine line) in /Users/therzok/Work/md/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs:line 61
   at Mono.TextEditor.TextArea.RenderMargins(Cairo.Context cr, Cairo.Context textViewCr, Rectangle cairoRectangle) in /Users/therzok/Work/md/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs:line 2231
   at Mono.TextEditor.TextArea.ExposeEventInternal(Gdk.EventExpose e) in /Users/therzok/Work/md/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs:line 2315
   at Mono.TextEditor.TextArea.OnExposeEvent(Gdk.EventExpose e) in /Users/therzok/Work/md/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs:line 2293
   at Gtk.Widget.exposeevent_cb(IntPtr widget, IntPtr evnt) in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/gtk-sharp-None/gtk/generated/Widget.cs:line 1349
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run() in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:line 145
   at MonoDevelop.Ide.IdeApp.Run() in /Users/therzok/Work/md/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs:line 459
   at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options) in /Users/therzok/Work/md/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 333
   at MonoDevelop.Ide.IdeStartup.Main(System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) in /Users/therzok/Work/md/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 735
   at MonoDevelop.Startup.MonoDevelopMain.Main(System.String[] args) in /Users/therzok/Work/md/monodevelop/main/src/core/MonoDevelop.Startup/MonoDevelop.Startup/MonoDevelopMain.cs:line 39
```

**Comment by KirillOsenkov** [comment]
@Therzok thanks for reporting, but we can't repro. If you can see it again, please send us more details: which branch, which exact build, which OS, .zip the project you're playing with, and try to remember which file content and which edit action you're doing.

We just spent 20 minutes with Todd trying to repro but we couldn't.

Thanks!
