### ISSUE TITLE
IntroduceVariableCodeRefactoringProvider error

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#5601]
Build Information
Release ID: 707000768
Git revision: 3f572451cf079a5a78a98eb78c026530f214e6c7
Build date: 2018-07-30 11:01:08+00
Build branch: master
Xamarin extensions: 720cda319c3eb5d8b8285d7cb7771d763fd86c13

No known repro. Was selecting some text in a class in md-addins.

```
 Roslyn reported an exception to the user
System.ArgumentOutOfRangeException: 'end' must not be less than 'start'
Parameter name: end
  at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds (System.Int32 start, System.Int32 end) [0x00028] in /_/src/Compilers/Core/Portable/Text/TextSpan.cs:191 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].GetExpressionUnderSpan (Microsoft.CodeAnalysis.SyntaxTree tree, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x000b7] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:201 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].TryInitialize (Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x00045] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:67 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+State[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].Generate (TService service, Microsoft.CodeAnalysis.SemanticDocument document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Threading.CancellationToken cancellationToken) [0x00008] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.State.cs:47 
  at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6+<IntroduceVariableAsync>d__17[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax].MoveNext () [0x000a7] in /_/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs:61 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at Microsoft.CodeAnalysis.CodeRefactorings.IntroduceVariable.IntroduceVariableCodeRefactoringProvider+<ComputeRefactoringsAsync>d__0.MoveNext () [0x00076] in /_/src/Features/Core/Portable/CodeRefactorings/IntroduceVariable/IntroduceVariableCodeRefactoringProvider.cs:26 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 
  at Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService+<GetRefactoringFromProviderAsync>d__8.MoveNext () [0x000a0] in /_/src/Features/Core/Portable/CodeRefactorings/CodeRefactoringService.cs:143 
```

> VS bug [#659693](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/659693)

**Comment by Therzok** [comment]
Maybe upstream against roslyn?

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/issues/28665

**Comment by mkrueger** [comment]
Closing - fixed in roslyn we'll get it at one of the next roslyn bumps.

**Comment by mrward** [comment]
This has been reported on the developer community forum - https://developercommunity.visualstudio.com/content/problem/318961/constant-error-notification-with-text-introducevar.html

**Comment by sevoku** [comment]
Reopening until Roslyn is bumped.

**Comment by sinanaltaii** [comment]
System.ArgumentOutOfRangeException : 'end' must not be less than 'start'
Parameter name: end
   at Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(Int32 start,Int32 end)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.GetExpressionUnderSpan(SyntaxTree tree,TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.TryInitialize(TextSpan textSpan,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.State.Generate(TService service,SemanticDocument document,TextSpan textSpan,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
