### ISSUE TITLE
AddinManagerDialog: Gtk-Warning: Can't set a parent on widget which has a parent

### ISSUE THREAD

**Issue by KirillOsenkov** [mono/monodevelop#5743]
7.6.1 (release-7.6 branch)

This happened when I opened the addin manager.

```
WARNING [2018-08-22 10:41:10Z]: Gtk-Warning: Can't set a parent on widget which has a parent

Stack trace: 
   at Gtk.Widget.gtk_widget_set_parent(IntPtr raw, IntPtr parent)
   at Gtk.Widget.set_Parent(Widget value)
   at Mono.Addins.Gui.AddinManagerDialog.OnShown() in C:\monodevelop\main\external\mono-addins\Mono.Addins.Gui\Mono.Addins.Gui\AddinManagerDialog.cs:line 190
   at Gtk.Widget.shown_cb(IntPtr widget)
   at Gtk.Dialog.gtk_dialog_run(IntPtr raw)
   at Gtk.Dialog.Run()
   at Mono.Addins.Gui.AddinManagerWindow.Run(Window parent, SetupService service) in C:\monodevelop\main\external\mono-addins\Mono.Addins.Gui\Mono.Addins.Gui\AddinManagerWindow.cs:line 77
   at Mono.Addins.Gui.AddinManagerWindow.Run(Window parent) in C:\monodevelop\main\external\mono-addins\Mono.Addins.Gui\Mono.Addins.Gui\AddinManagerWindow.cs:line 69
   at MonoDevelop.Ide.Updater.AddinsUpdateHandler.<ShowManager>d__9.MoveNext() in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Updater\AddinsUpdateHandler.cs:line 116
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at MonoDevelop.Ide.Updater.AddinsUpdateHandler.ShowManager()
   at MonoDevelop.Ide.Commands.AddinManagerHandler.Run() in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Commands\ToolsCommands.cs:line 53
   at MonoDevelop.Components.Commands.CommandHandler.Run(Object dataItem) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandHandler.cs:line 70
   at MonoDevelop.Components.Commands.CommandHandler.InternalRun(Object dataItem) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandHandler.cs:line 39
   at MonoDevelop.Components.Commands.CommandManager.DefaultDispatchCommand(ActionCommand cmd, CommandInfo info, Object dataItem, Object target, CommandSource source) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:line 1584
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(Object commandId, Object dataItem, Object initialTarget, CommandSource source, Nullable`1 time, CommandInfo sourceUpdateInfo) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:line 1547
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(Object commandId, Object dataItem, Object initialTarget, CommandSource source) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Components.Commands\CommandManager.cs:line 1388
   at WindowsPlatform.MainToolbar.TitleMenuItem.<OnMenuClicked>b__9_0() in C:\monodevelop\main\src\addins\WindowsPlatform\WindowsPlatform\MainToolbar\TitleMenuItem.cs:line 238
   at Xwt.Toolkit.Invoke(Action a) in C:\monodevelop\main\external\xwt\Xwt\Xwt\Toolkit.cs:line 470
   at Xwt.Application.<>c__DisplayClass24_0.<Invoke>b__0() in C:\monodevelop\main\external\xwt\Xwt\Xwt\Application.cs:line 197
   at Xwt.GtkBackend.GtkEngine.<>c__DisplayClass9_0.<InvokeAsync>b__0(Object o, EventArgs args) in C:\monodevelop\main\external\xwt\Xwt.Gtk\Xwt.GtkBackend\GtkEngine.cs:line 233
   at Gtk.Application.InvokeCB.Invoke()
   at GLib.Timeout.TimeoutProxy.Invoke(IntPtr data)
   at GLib.SourceProxy.HandlerInternal(IntPtr data)
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at MonoDevelop.Ide.IdeApp.Run() in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide\Ide.cs:line 456
   at MonoDevelop.Ide.IdeStartup.Run(MonoDevelopOptions options) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide\IdeStartup.cs:line 332
   at MonoDevelop.Ide.IdeStartup.Main(String[] args, IdeCustomizer customizer) in C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide\IdeStartup.cs:line 734
   at MonoDevelop.Startup.MonoDevelopMain.Main(String[] args) in C:\monodevelop\main\src\core\MonoDevelop.Startup\MonoDevelop.Startup\MonoDevelopMain.cs:line 39
```

**Comment by Therzok** [comment]
Related: https://github.com/mono/mono-addins/commit/691bdb6604155e9b18a038382b527ae09d995f43

**Comment by KirillOsenkov** [comment]
Seeing this in 7.6.5.20 too.
