### ISSUE TITLE
Unable to start on Raspbian bullseye (SIGSEGV while executing native code)

### ISSUE THREAD

**Issue by schellingb** [mono/monodevelop#9649]
Hi there

I just installed MonoDevelop from the Raspbian 9 (armhf) repository as explained on the [download page](https://www.monodevelop.com/download/#fndtn-download-lin-raspbian) but it crashes on startup. It shows a window with a title bar and the correct icon, but the content of the window stays gray until the crash.

Here's the output of `monodevelop --no-redirect`:
[monodevelop-crash-log.txt](https://github.com/mono/monodevelop/files/5178609/monodevelop-crash-log.txt)

I also tried running it as `mono --debug /usr/lib/monodevelop/bin/MonoDevelop.exe --no-redirect` or through GDB but the output was not much different. This is all I get out of gdb at the segfault:
```
Thread 1 "monodevelop" received signal SIGSEGV, Segmentation fault.
0xb2bd3408 in ?? () from /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
(gdb) bt
#0  0xb2bd3408 in  () at /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
#1  0xb2bd8058 in g_main_context_dispatch () at /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
#2  0x00000000 in  ()
```
Installing libglib2.0-dev did not help.

I have Mono 6.10.0.104 from the same repository as MonoDevelop installed. I'm running lxde and uname -a prints `Linux pi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux`. As mentioned, I am running Raspbian bullseye so maybe there's some weird incompatibility.

I also tried installing from preview-raspbianbuster (alongside preview-raspbianstretch because the buster repository does not seem to contain the monodevelop package) but the result seems exactly the same.

Anything else I could try?
Thanks!

**Comment by schellingb** [comment]
I'm not interested in this anymore and Raspbian bullseye is not the stable distribution anyway so I'm closing this issue.
